# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1b9aa7d14f156320159d6d50cf253d41d62c6303dce33d034779aabb3abefcd3ed378831441961dabf2cde9c818d8d71bf1a27a4d8341014746c33dfcf813e7

test:
  secret_key_base: dbc796e0e8246a21213aa3e6cc64f2758e7bc2601c1c2a53b7b2f8b0462cfc41288ed3c4768e81b913a0488a518fc72b18f9b2d637adb5553230ba0f503b151a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
